
package it.accenture.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceManager", targetNamespace = "http://ws.accenture.it/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceManager {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saluti", targetNamespace = "http://ws.accenture.it/", className = "it.accenture.ws.Saluti")
    @ResponseWrapper(localName = "salutiResponse", targetNamespace = "http://ws.accenture.it/", className = "it.accenture.ws.SalutiResponse")
    @Action(input = "http://ws.accenture.it/WebServiceManager/salutiRequest", output = "http://ws.accenture.it/WebServiceManager/salutiResponse")
    public String saluti();

    /**
     * 
     * @param id
     * @return
     *     returns it.accenture.ws.Atleta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recuperoAtleta", targetNamespace = "http://ws.accenture.it/", className = "it.accenture.ws.RecuperoAtleta")
    @ResponseWrapper(localName = "recuperoAtletaResponse", targetNamespace = "http://ws.accenture.it/", className = "it.accenture.ws.RecuperoAtletaResponse")
    @Action(input = "http://ws.accenture.it/WebServiceManager/recuperoAtletaRequest", output = "http://ws.accenture.it/WebServiceManager/recuperoAtletaResponse")
    public Atleta recuperoAtleta(
            @WebParam(name = "id", targetNamespace = "")
            Long id);

    /**
     * 
     * @return
     *     returns java.util.List<it.accenture.ws.Gara>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recuperoAllGare", targetNamespace = "http://ws.accenture.it/", className = "it.accenture.ws.RecuperoAllGare")
    @ResponseWrapper(localName = "recuperoAllGareResponse", targetNamespace = "http://ws.accenture.it/", className = "it.accenture.ws.RecuperoAllGareResponse")
    @Action(input = "http://ws.accenture.it/WebServiceManager/recuperoAllGareRequest", output = "http://ws.accenture.it/WebServiceManager/recuperoAllGareResponse")
    public List<Gara> recuperoAllGare();

    /**
     * 
     * @param id
     * @return
     *     returns it.accenture.ws.Gara
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recuperoGara", targetNamespace = "http://ws.accenture.it/", className = "it.accenture.ws.RecuperoGara")
    @ResponseWrapper(localName = "recuperoGaraResponse", targetNamespace = "http://ws.accenture.it/", className = "it.accenture.ws.RecuperoGaraResponse")
    @Action(input = "http://ws.accenture.it/WebServiceManager/recuperoGaraRequest", output = "http://ws.accenture.it/WebServiceManager/recuperoGaraResponse")
    public Gara recuperoGara(
            @WebParam(name = "id", targetNamespace = "")
            Long id);

    /**
     * 
     * @return
     *     returns java.util.List<it.accenture.ws.Atleta>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recuperoAllAtleti", targetNamespace = "http://ws.accenture.it/", className = "it.accenture.ws.RecuperoAllAtleti")
    @ResponseWrapper(localName = "recuperoAllAtletiResponse", targetNamespace = "http://ws.accenture.it/", className = "it.accenture.ws.RecuperoAllAtletiResponse")
    @Action(input = "http://ws.accenture.it/WebServiceManager/recuperoAllAtletiRequest", output = "http://ws.accenture.it/WebServiceManager/recuperoAllAtletiResponse")
    public List<Atleta> recuperoAllAtleti();

}
